### ISSUE TITLE
pngcrush collapsed

### ISSUE THREAD

**Issue by Garretthh07** [Kjuly/pngcrush#2]
When I run `pngcrush` in Ms-dos, I got the problem below:

        应用程序无法正常启动(0xc000007b). 请单击 " 确定" 关闭应用程序.

But sometiems, it can run perfectly.

**Comment by Kjuly** [comment]
Sorry, i'm not quite familiar w/ MS-DOS.
MS-DOS version script is contributed by @madpew https://github.com/Kjuly/pngcrush/pull/1. Hi @madpew , have u ever met this issue before? Any advice?

**Comment by Garretthh07** [comment]
I have googled some reasons,  maybe this cannot run perfectly on windows 32bit, because it is developed on windows 64bit? More...

    http://www.tomshardware.com/answers/id-1991597/windows-bit-error-0xc000007b.html

**Comment by Kjuly** [comment]
hm.. not sure. Maybe u can try [Trimage](https://trimage.org), which embed pngcrush along with other commandline image compressors/optimizers, it has Windows version as well. Hope it helps. :)

**Comment by madpew** [comment]
Never ran into any issues like that. The mentioned errorcode (0xc000007b) can be caused by a lot of things going wrong. Did you compile pngcrush yourself (on that machine or a different one) or are you using a precompiled version? Might help getting a clue but I can't think of any reasons why it should crash sometimes opposed to everytime. Maybe something wrong with the files you try to process?

**Comment by Garretthh07** [comment]
@Kjuly  Thanks for your recommend. 

@madpew 
- Sorry for that, i will pay attention for it.
- Yes, I compile it myself on windows 64bit, different one
-  Only compile this project, which I ·clone· on Github
- I find another Windows PC which is 64bit, it can run perfectly
  But when I run it on 32bit PC, it crashed, I have tested two 32bit PC, performed the same
- I will check if  I went wrong something. 
- Thank you for your patience

**Comment by Kjuly** [comment]
Just a note here: i've updated the pngcrush lib to latest 1.8.1 just now, try it if u want. :)

**Comment by Garretthh07** [comment]
@Kjuly  Thank you very much. I wil  have a try.

**Comment by Garretthh07** [comment]
@Kjuly  After updated to 1.8.1, whether it is Win 64bit or Win 32bit. `pngcrush` can run perfectly. 

     Thanks very much.

**Comment by Kjuly** [comment]
@Garretthh07 👍
