### ISSUE TITLE
..\pngcrush\pngcrush不是外部或内部命令

### ISSUE THREAD

**Issue by smartwange** [Kjuly/pngcrush#6]

**Comment by Kjuly** [comment]
请问 `pngcrush/` 文件夹下的 `pngcrush.o` 是否存在？如果不存在，可通过 `make` 手动编译。

**Comment by smartwange** [comment]
> 请问 `pngcrush/` 文件夹下的 `pngcrush.o` 是否存在？如果不存在，可通过 `make` 手动编译。

make clean 无效
command  not found

**Comment by Kjuly** [comment]
如果拉取该资源后未做更改，`pngcrush.o` 以及可执行文件 `pngcrush` 是应该存在的。可能未授予执行权限，可以尝试：
    
    $ cd ./path/to/pngcrush
    $ chmod +x pngcrush
