### ISSUE TITLE
Support macOS Catalina - 10.15

### ISSUE THREAD

**Issue by raykle** [Kjuly/pngcrush#7]
pngcrush has been removed when upgraded to macOS 10.15 since it is 32-bit.

**Comment by Kjuly** [comment]
@raykle sorry, haven't upgraded my system yet, will take a look when do.

**Comment by Kjuly** [comment]
Seems it works under 64-bit system. You can try `$ make` if your executable binary file was removed; or just re-pull this repo to use the one generated inside.

Btw, my envir is macOS 10.15.3 (19D76).

**Comment by raykle** [comment]
Thank you. I'll try it. 👍
